import { PricingPlan, PricingTier } from '@types/index';

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'basic',
    name: 'Paquete 1',
    title: 'Básico',
    price: '$300/mes',
    period: 'por mes',
    features: [
      'Disfruta de las instalaciones de SportClub',
      'Entrenamientos básicos',
      'Consultas',
      'Productos',
    ],
    image: '/img/40.jpeg',
    featured: false,
    cta: 'Empieza ahora',
    ctaLink: '/login',
    tier: PricingTier.BASIC,
  },
  {
    id: 'socio',
    name: 'Paquete 2',
    title: 'SportSocio',
    price: '$900',
    period: 'cada 3 meses',
    features: [
      'Instalaciones de SportClub',
      'Entrenamientos básicos y personalizados',
      'Consultas de rutinas y alimentación',
      'Áreas especiales',
      'Productos',
    ],
    image: '/img/41.jpeg',
    featured: true,
    cta: 'Empieza ahora',
    ctaLink: '/login',
    tier: PricingTier.SOCIO,
  },
  {
    id: 'premium',
    name: 'Paquete 3',
    title: 'SportClub Premium',
    price: '$3000',
    period: 'anualidad',
    features: [
      'Acceso a todas las instalaciones',
      'Entrenamientos básicos y personalizados',
      'Consultas ilimitadas de rutinas y alimentación',
      'Acceso a áreas especiales sin limitación',
      'Productos sin restricción',
      'Descuento amigos',
    ],
    image: '/img/22.jpg',
    featured: false,
    cta: 'Empieza ahora',
    ctaLink: '/login',
    tier: PricingTier.PREMIUM,
  },
];
